name: pageable_stream
description: A Dart package that provides an efficient and easy-to-use implementation of paginated streaming. This package is designed to handle large datasets by loading them in chunks (pages) while providing a seamless Stream interface.
version: 1.0.0
homepage: https://github.com/cristovao/pageable_stream
repository: https://github.com/cristovao/pageable_stream
issue_tracker: https://github.com/cristovao/pageable_stream/issues

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
